name: Azure Policy Assignment

on:
  push:
    branches:
      - main
    paths:
      - 'policy/**'

jobs:
  apply-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ./policy
        run: terraform init

      - name: Terraform Plan
        working-directory: ./policy
        run: terraform plan -var="tf_organization=${{ vars.TF_ORGANIZATION }}" -var="tf_policy_workspace=${{ vars.TF_POLICY_WORKSPACE }}"

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./policy
        run: terraform apply -auto-approve -var="tf_organization=${{ vars.TF_ORGANIZATION }}" -var="tf_policy_workspace=${{ vars.TF_POLICY_WORKSPACE }}"